stages:
 - mavenbuild
 - maventest
 - autodeploy
 - fluttertest
 - flutterbuild

maven-build:
 stage: mavenbuild
 tags:
 - shell
 script:
 - cd BackEnd/springboot_backend/
 - mvn package -B

maven-test:
 stage: maventest
 tags:
 - shell
 script:
 - cd BackEnd/springboot_backend/
 - mvn test
 artifacts:
  paths:
  - BackEnd/springboot_backend/target/*.jar

auto-deploy2:
 stage: autodeploy
 tags:
 - shell
 script:
 - cd BackEnd/springboot_backend/
 - mvn package
 - sudo mv target/*.jar /target/web-demo.jar
 - sudo systemctl stop web-demo
 - sudo systemctl start web-demo


auto-deploy3:
 stage: autodeploy
 tags:
 - shell
 only: 
  refs:
  - master
  variables:
  - $CI_COMMIT_MESSAGE =~ /autodeploy/
 script:
 - cd BackEnd/springboot_backend/
 - mvn package
 - sudo mv target/*.jar /target/web-demo.jar
 - sudo systemctl stop web-demo
 - sudo systemctl start web-demo
 

flutter-test:
 stage: fluttertest
 before_script:
 - export PATH=$PATH:/home/gitlab-runner/flutter/flutter/bin/
 tags:
  - flutter
 script:
  - cd FrontEnd/risk/
  - flutter test
  
 
flutter-build:
 stage: flutterbuild
 before_script:
 - export ANDROID_HOME=/home/gitlab-runner/android-sdk
 - export PATH=$PATH:/home/gitlab-runner/flutter/flutter/bin/
 - export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
 tags:
 - flutter
 script:
 - cd FrontEnd/risk
 - flutter pub get && flutter clean && flutter build apk --debug --target-platform android-arm,android-arm64 --split-per-abi
 - sudo mv build/app/outputs/apk/debug/app-arm64-v8a-debug.apk /target/app-arm64.apk
 - sudo mv build/app/outputs/apk/debug/app-armeabi-v7a-debug.apk /target/app-armeabi.apk

